## キュー待ちのサーバー (何個でも可能)
targetServer: |
  lobby
## 送るサーバー
sendServer: main

## 指定された時間ごとにプレイヤーを送る ミリ秒 (初期 2秒)
queueTime: 2000
## queueTimeごとに送るプレイヤーの人数 (初期5人)
sendToPlayers: 5
## 1プレイヤーを送るのにかかる時間 (初期 0.05秒)
sendToPlayersTime: 50